---
version: "3"

networks:
  celestia-stack:

services:
  celestia-node:
    image: ghcr.io/celestiaorg/celestia-node:v0.9.3
    command: [
      "celestia", "light", "start",
      "--core.ip", "https://rpc-blockspacerace.pops.one",
      "--gateway",
      "--gateway.addr", "127.0.0.1",
      "--gateway.port", "26659",
      "--p2p.network", "blockspacerace"
    ]
    environment:
      - NODE_TYPE=light
      - P2P_NETWORK=blockspacerace
    restart: unless-stopped
    networks:
      - celestia-stack
    volumes:
      - "./volumes/celestia-node-light:/home/celestia"
