{
 "title": "Celestia App Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Voting Power (validator only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "celestia_validator_info_voting_power",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catching up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "celestia_sync_info_catchingup", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latest block height rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(celestia_sync_info_latest_block_height[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest block time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "celestia_sync_info_latest_block_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest block height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "celestia_sync_info_latest_block_height",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}